# Generated by Django 5.0.6 on 2024-07-06 07:23

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/media/avatar.jpeg', upload_to=users.utils.user_directory_path),
        ),
    ]
